"""Deterministic mock LLM client for local and test execution."""

from typing import TypeVar

from pydantic import BaseModel

from app.llm.client import LLMClient
from app.llm.schemas import (
    CandidateExplanationOutput,
    Citation,
    CriticReviewOutput,
    EvidenceAssemblyOutput,
    FeatureCriticOutput,
    GuardrailReviewOutput,
    JudgePanelOutput,
    ModelExplanationOutput,
    PlannerDecisionOutput,
    RecommendedPySparkFeature,
    TransactionBehaviourOutput,
    TypologyMappingOutput,
)

StructuredResponseT = TypeVar("StructuredResponseT", bound=BaseModel)


class MockLLMClient(LLMClient):
    """Schema-aware deterministic LLM client."""

    def __init__(self, model_name: str = "mock-aml-llm", temperature: float = 0.0, timeout: float = 10.0) -> None:
        self.model_name = model_name
        self.temperature = temperature
        self.timeout = timeout

    def generate_structured(self, prompt: str, response_schema: type[StructuredResponseT]) -> StructuredResponseT:
        """Return deterministic output matching the requested schema."""
        payload = self._payload_for_schema(response_schema, prompt)
        return response_schema.model_validate(payload)

    def generate_text(self, prompt: str) -> str:
        """Return deterministic text."""
        return f"Mock response generated by {self.model_name} for prompt length {len(prompt)}."

    def _payload_for_schema(self, response_schema: type[BaseModel], prompt: str) -> dict[str, object]:
        if response_schema is TransactionBehaviourOutput:
            return {
                "behavioural_summary": (
                    "The activity shows elevated velocity and counterparty changes relative to baseline."
                ),
                "abnormal_patterns": [
                    "Velocity change is elevated over the recent window.",
                    "New counterparty ratio may be higher than expected.",
                    "Counterparty concentration should be reviewed.",
                ],
                "baseline_comparison": (
                    "Recent behaviour is above the synthetic historical baseline for frequency and amount."
                ),
                "key_features": {
                    "velocity_change": "Higher recent transaction count than baseline.",
                    "new_counterparty_ratio": "Share of counterparties not previously observed.",
                    "cross_border_amount_ratio": "Share of amount sent cross-border.",
                    "active_hours_entropy": "Dispersion of activity across hours.",
                    "in_out_amount_ratio": "Relationship between incoming and outgoing value.",
                    "counterparty_concentration": "Share of activity tied to top counterparty.",
                    "amount_spike": "Recent value increase against baseline.",
                    "round_amount_pattern": "Repeated round amount behaviour.",
                },
                "uncertainty": "This is an analytical signal from synthetic data and requires corroborating context.",
                "evidence_items": [
                    {
                        "source": "transactions",
                        "reference": "customer_transactions",
                        "description": "Recent customer transaction sample reviewed.",
                        "value": "synthetic",
                    }
                ],
            }
        if response_schema is ModelExplanationOutput:
            return {
                "model_summary": "The model score indicates elevated anomaly risk for review prioritization.",
                "top_risk_drivers": ["reconstruction_error", "velocity_spike", "counterparty_concentration"],
                "score_interpretation": "The score is not proof of suspicious activity; it is a prioritization signal.",
                "model_uncertainty": (
                    "Model uncertainty remains because training context and feature lineage are not loaded."
                ),
                "feature_directionality": {
                    "reconstruction_error": "Higher values generally increase anomaly concern.",
                    "new_counterparty_ratio": "Higher values may increase risk depending on segment.",
                },
                "caveats": ["Model score is not proof of suspicious activity.", "Business context is required."],
            }
        if response_schema is CandidateExplanationOutput:
            return {
                "summary": "This customer was prioritized by the selected model based on elevated model drivers.",
                "model_reasoning": (
                    "The score is a model-driven prioritization signal based only on the supplied feature evidence."
                ),
                "feature_driver_explanation": (
                    "The listed feature drivers contributed most to the model ranking for this customer."
                ),
                "suggested_investigator_focus": [
                    "Review the transactions connected to the top model drivers.",
                    "Compare activity against expected customer profile before disposition.",
                ],
                "limitations": ["Model output is not proof of suspicious activity."],
            }
        if response_schema is TypologyMappingOutput:
            return {
                "matched_typologies": ["Velocity spike", "Counterparty concentration"],
                "supporting_indicators": [
                    "Activity resembles indicators associated with rapid movement of funds.",
                    "Network concentration may warrant further review.",
                ],
                "citations": [
                    Citation(
                        doc_id="KB001",
                        title="FINTRAC suspicious transaction indicators",
                        source="Synthetic FINTRAC typology digest",
                        url="https://fintrac-canafe.canada.ca/",
                    ).model_dump()
                ],
                "missing_evidence": ["Purpose of transactions", "Customer stated business rationale"],
                "confidence": 0.72,
                "careful_language_summary": (
                    "Observed behaviour resembles indicators associated with AML typologies and may warrant further "
                    "review; evidence is insufficient to conclude suspicious or criminal activity."
                ),
            }
        if response_schema is FeatureCriticOutput:
            return {
                "feature_quality_findings": [
                    "Velocity and counterparty features are explainable but need stability tests."
                ],
                "unstable_features": ["active_hours_entropy", "new_counterparty_ratio"],
                "possible_leakage_risks": ["Features using post-alert outcomes could leak investigation decisions."],
                "missing_feature_opportunities": ["Dormancy break velocity", "Counterparty country concentration"],
                "recommended_pyspark_features": [
                    RecommendedPySparkFeature(
                        feature_name="cross_border_amount_ratio_30d",
                        business_rationale="Captures concentration of cross-border value over a recent window.",
                        formula_description=(
                            "Sum cross-border outgoing amount over 30 days divided by total outgoing amount."
                        ),
                        required_columns=["customer_id", "timestamp", "amount", "direction", "is_cross_border"],
                        edge_cases=["No outgoing amount", "Currency conversion gaps"],
                        leakage_risk="Low if calculated only from transactions before scoring time.",
                        expected_direction="Higher ratio may increase review priority.",
                        pyspark_pseudocode=(
                            "df.groupBy('customer_id').agg("
                            "sum(when(col('is_cross_border'), col('amount')).otherwise(0)) / sum('amount'))"
                        ),
                    ).model_dump()
                ],
                "validation_tests": ["Population stability index by month", "Null-rate drift by segment"],
            }
        if response_schema is PlannerDecisionOutput:
            completed_segment = prompt.split('"completed_agents":', 1)[1].split("]", 1)[0]
            if "transaction_behaviour_agent" not in completed_segment:
                next_action = "transaction_behaviour_agent"
                reason = "No transaction behaviour evidence has been recorded yet."
                missing_evidence = ["customer transaction behaviour"]
            elif "typology_mapping_agent" not in completed_segment:
                next_action = "typology_mapping_agent"
                reason = "Transaction behaviour is available, so typology context should be checked next."
                missing_evidence = ["typology mapping"]
            elif "case_investigation_agent" not in completed_segment:
                next_action = "case_investigation_agent"
                reason = "Behaviour and typology context are available; case disposition evidence is still missing."
                missing_evidence = ["case investigation feedback"]
            else:
                next_action = "finalize_report"
                reason = "Required investigator evidence has been gathered and the draft can be assembled."
                missing_evidence = []
            return {
                "next_action": next_action,
                "reason": reason,
                "evidence_checked": ["completed agent outputs in state"],
                "missing_evidence": missing_evidence,
                "stop_reason": reason if next_action == "finalize_report" else None,
                "confidence": 0.84,
            }
        if response_schema is EvidenceAssemblyOutput:
            return {
                "report_markdown": (
                    "# AML Intelligence Report\n\n"
                    "## Executive Summary\nRouted analysis completed using available evidence.\n\n"
                    "## Customer Behaviour Overview\nBehaviour section included when behaviour agent ran.\n\n"
                    "## Limitations and Uncertainty\nSynthetic data and mock LLM outputs require validation."
                ),
                "included_sections": [
                    "Executive Summary",
                    "Customer Behaviour Overview",
                    "Limitations and Uncertainty",
                    "Recommended Analytical Next Steps",
                ],
                "evidence_table": [{"agent": "mock", "evidence": "schema-valid evidence"}],
                "limitations_and_uncertainty": ["Synthetic data only.", "No real LLM provider configured."],
                "recommended_next_steps": ["Review source transactions.", "Validate feature stability."],
            }
        if response_schema is CriticReviewOutput:
            return {
                "status": "needs_refinement",
                "issues": [
                    (
                        "Draft should explicitly connect the investigator case review to the typology and "
                        "behaviour evidence."
                    )
                ],
                "target_section": "Investigator Case Review",
                "refinement_instruction": (
                    "Strengthen the case review section by tying disposition feedback back to evidence already "
                    "gathered."
                ),
                "must_refine": True,
                "confidence": 0.81,
            }
        if response_schema is JudgePanelOutput:
            return {
                "groundedness": 0.82,
                "coverage": 0.78,
                "governance_readiness": 0.8,
                "rationale": "Mock judge found outputs structured, cautious, and evidence-linked.",
            }
        if response_schema is GuardrailReviewOutput:
            return {
                "status": "passed",
                "flags": [],
                "safe_summary": "Output uses careful language and avoids prohibited conclusions.",
                "required_disclaimers": ["Model and typology outputs are analytical aids, not determinations."],
            }
        return {}
